### PR TITLE
Update w64wow64.c

### PR DESCRIPTION
**Pull request by justanotheranonymoususer**
I'm not sure, but shouldn't these be ORs?

### CODE REVIEW

**Comment by georgenicolaou** [comment]
Correct, although I doubt addition is an issue in this case you never know. Plus it's more readable this way, thanks

**Comment by justanotheranonymoususer** [comment]
By the way, how is this project different from https://github.com/rwfpl/rewolf-wow64ext/?

**Comment by georgenicolaou** [comment]
This project is a fork of rewolf-wow64ext. What W64oWoW64 does differently is the algorithm at InitializeW64oWoW64()

**Comment by justanotheranonymoususer** [comment]
I think that you should mention this in the README. Also, your code crashes on AMD. See:
https://github.com/rwfpl/rewolf-wow64ext/commit/8771485dd3460dc8f995265b16e2a9791d015fd8

**Comment by georgenicolaou** [comment]
Updated the readme you are correct. I uploaded it before rewolf had his on github. 
This library is not affected by that issue since my base system is AMD, it was one of the reasons that I had to re-write the code for X64_Call(), to understand it and to fix the problem on my platform

**Pull request merged**
